### ISSUE TITLE
ImportError in cly.pi

### ISSUE THREAD

**Issue by gerard33** [bimmerconnected/bimmer_connected#133]
When running `cli.py` I get this error.

```py
File "cli.py", line 11, in <module>
    from bimmer_connected.vehicle import VehicleViewDirection, PointOfInterest
ImportError: cannot import name 'PointOfInterest'

```

**Comment by robthebold** [comment]
Is it possible that cli.py is trying to import PointOfInterest from the pip-installed library version of bimmer_connected/vehicle.py rather than the latest version in your devel directory?

**Comment by robthebold** [comment]
I get the same issues if I don't update the source in ~/.local/lib/python3.5/site-packages/bimmer_connected/ to match the changes I've made. Apparently python looks in the pip installed library before looking locally for imports.

**Comment by rikroe** [comment]
How are you guys running `cli`? Using `python -m bimmer_connected.cli` or `python bimmer_connected/cli.py`? 
Also, could it be that as Rob mentioned you are mixing up `dev` and `pypi` versions? Just did a clean install of `bimmer_connected==0.6.2` in a fresh `venv` and everythings works as it should.

**Comment by gerard33** [comment]
Will have a look at it, probably something I did wrong indeed :sunglasses:

**Comment by robthebold** [comment]
At least on Ubuntu 16.04 with python 3.5.2, I've found that python will first look in a subdirectory named, e.g. bimmer_connected before searching installed packages called "bimmer_connected". So if cli.py lives in the directory one level up from subdir "bimmer_connected", all the imports will first be searched for in the bimmer_connected directory. So I've taken to moving cli.py up one directory level whenever I need to test against any new/experimental library stuff rather than the pip3 installed version.

Before I noticed this behavior, I kept scratching (and beating) my head wondering why something that I had _just added_ to a module couldn't be imported!
