### ISSUE TITLE
Question-command line interface

### ISSUE THREAD

**Issue by 2bbe** [bimmerconnected/bimmer_connected#147]
Tank you for your great work.
I’m not using HA and trying to integrate the script in my system using the CLI.
Requesting status works great but I’m having trouble with remote commands.
I’m using the example function for light flash with the following arguments and get 500 error.
lightflash user password rest_of_world vin 
Am I calling the function correctly?

My goal is to get the remote ac working so I can trigger it from my home automation system and I assume that when I get the lightflash working it’s only a matter of adapting the example with trigger_remote_air_conditioning() instead of trigger_remote_light_flash() 

Br Tobias

**Comment by rikroe** [comment]
The following just worked for me on [release 0.7.0](https://github.com/bimmerconnected/bimmer_connected/releases/tag/0.7.0):
```
python -m bimmer_connected.cli lightflash user password rest_of_world VIN
```
Maybe your issue was due to BMW servers changing (#150). Can you please try again?

If you get air conditioning working in `cli`, would you create a PR including this feature?

**Comment by 2bbe** [comment]
Strange, I still get an error.
The Debug messages seems OK until calling ...serviceType=LIGHT_FLASH 

Debug messages below:
`DEBUG:bimmer_connected.account:Getting vehicle list
DEBUG:bimmer_connected.account:getting new oauth token
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): customer.bmwgroup.com:443
DEBUG:urllib3.connectionpool:https://customer.bmwgroup.com:443 "POST /gcdm/oauth/authenticate HTTP/1.1" 302 None
DEBUG:bimmer_connected.account:got new token [TOKEN] with expiration date 2020-02-18 00:13:42.383722
DEBUG:bimmer_connected.account:Old token is still valid. Not getting a new one.
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): b2vapi.bmwgroup.com:443
DEBUG:urllib3.connectionpool:https://b2vapi.bmwgroup.com:443 "GET /webapi/v1/user/vehicles HTTP/1.1" 200 None
DEBUG:bimmer_connected.remote_services:Triggering remote light flash
DEBUG:bimmer_connected.account:Old token is still valid. Not getting a new one.
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): b2vapi.bmwgroup.com:443
DEBUG:urllib3.connectionpool:https://b2vapi.bmwgroup.com:443 "POST /webapi/v1/user/vehicles/[VIN]/executeService HTTP/1.1" 200 None
DEBUG:bimmer_connected.remote_services:getting remote service status
DEBUG:bimmer_connected.account:Old token is still valid. Not getting a new one.
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): b2vapi.bmwgroup.com:443
DEBUG:urllib3.connectionpool:https://b2vapi.bmwgroup.com:443 "GET /webapi/v1/user/vehicles/[VIN]/serviceExecutionStatus?serviceType=LIGHT_FLASH HTTP/1.1" 500 None
DEBUG:bimmer_connected.account:Error 500 on attempt 1`
@rikroe - could you please share your debuglog four faultfinding?

I will ofcourse create a PR with my update if I get it working

**Comment by rikroe** [comment]
I have exactly the same debug output, except I'm getting a `200` on `executeService`.
Can you try again? Maybe BMW got some hickups (they surely got some in the last days...) and now it works for you again like in #154?

Otherwise, whats the output of `python -m bimmer_connected.cli fingerprint username password rest_of_world`?

**Comment by 2bbe** [comment]
Still same 500 error with both server addresses:(
Strange that the fingerprint(see attached) and status functions works 

[status_0.txt](https://github.com/bimmerconnected/bimmer_connected/files/4227000/status_0.txt)
[vehicles_0.txt](https://github.com/bimmerconnected/bimmer_connected/files/4227001/vehicles_0.txt)

**Comment by rikroe** [comment]
Do you get the content of the API's 500 response somewhere in your logs (after the 5th attempt)?
I'm asking myself if you face the same issue as #146 where it seems like newer cars need some additional information/authentication.

If you have time and want to try something, can you test using my `newapi_bkp` branch from [https://github.com/rikroe/bimmer_connected/tree/newapi_bkp](https://github.com/rikroe/bimmer_connected/tree/newapi_bkp)? This uses some other REST endpoints and more steps in authentication. 

Otherwise I'll guess we have to MITM the traffic of an Android App very thoroughly...

**Comment by 2bbe** [comment]
Ill check your branch during this week. 
Here is the last parts of the log

`DEBUG:bimmer_connected.account:Error 500 on attempt 6
Traceback (most recent call last):
  File "/home/pi/.local/bin/bimmerconnected", line 11, in <module>
    sys.exit(main())
  File "/home/pi/.local/lib/python3.5/site-packages/bimmer_connected/cli.py", line 66, in main
    args.func(args)
  File "/home/pi/.local/lib/python3.5/site-packages/bimmer_connected/cli.py", line 126, in light_flash
    status = vehicle.remote_services.trigger_remote_light_flash()
  File "/home/pi/.local/lib/python3.5/site-packages/bimmer_connected/remote_services.py", line 77, in trigger_remote_light_flash
    return self._block_until_done(_Services.REMOTE_LIGHT_FLASH)
  File "/home/pi/.local/lib/python3.5/site-packages/bimmer_connected/remote_services.py", line 142, in _block_until_done
    status = self._get_remote_service_status(service)
  File "/home/pi/.local/lib/python3.5/site-packages/bimmer_connected/remote_services.py", line 165, in _get_remote_service_status
    return RemoteServiceStatus(json_result)
  File "/home/pi/.local/lib/python3.5/site-packages/bimmer_connected/remote_services.py", line 47, in __init__
    status = response['executionStatus']
KeyError: 'executionStatus'`

**Comment by 2bbe** [comment]
I finally got some time to test.
I tried the remote ac(trigger_remote_air_conditioning() ) from my adapted cli and got errors as above.

The good part of it is that the heating was running when I got to the car:)
