### ISSUE TITLE
Home assistant lock state not updating, but lock follows commands

### ISSUE THREAD

**Issue by doodlebro** [bimmerconnected/bimmer_connected#266]
**Describe the issue**

Experiencing this issue since bimmer_connected became an integration in HA. Before the integration, everything was working great.

The state of the lock never updates in HA and is stuck on "unknown." I have tried removing and reconfiguring the integration twice without success, but it's strange that the GPS location of the car has no issues updating HA and never returns "unknown."

**Expected behavior**

Lock state for my car should update as it changes state from any source.

Unlocking/locking the car with the keyfob does not update state in HA (it should). Unlocking/locking the car using the official BMW connected drive app does not update state in HA (it should). Using HA to lock/unlock the car works, but state never updates as it should.

**Home Assistant version (if used)**

2021.1.4

**Screenshots**

**ConnectedDrive website**

If you see any issues with the BMW integration in Home Assistant (or when directly using the library), please make sure to first login to the BMW ConnectedDrive website of your country and check if you can successfully login and query the car status.
- [x] I can still successfully login to the BMW ConnectedDrive website and the car status is available there.
- [x] I have ConnectedDrive enabled for my vehicle.

**Your config.yaml**

Using the integration now, config has been commented out.

**Number of cars**

1 car

If you have more than 1 car please mention that here.
- [ ] I have 2 or more cars linked to the ConnectedDrive account.
- [ ] I have a Mini vehicle linked to my account.

**Output of bimmer_connected fingerprint**

If you have run the [bimmer_connected fingerprint](https://github.com/bimmerconnected/bimmer_connected#data-contributions) please share that data here

[STATUS_0.txt](https://github.com/bimmerconnected/bimmer_connected/files/5863025/STATUS_0.txt)
[vehicles_0.txt](https://github.com/bimmerconnected/bimmer_connected/files/5863026/vehicles_0.txt)

*NOTE: It might take us a while to respond on GitHub (we only maintain this in our free time), but we will respond.*

**Comment by rikroe** [comment]
This is really weird because based on the *status.txt* you provided, it looks like it works as expected.
To display the current lock state of the vehicle, *status.txt* must contain something like: https://github.com/bimmerconnected/bimmer_connected/blob/b5ac1b53813348c2c808a5835a97984323c87685/test/responses/G31_NBTevo/status.json#L44

Sorry for the question, but are you sure it actually worked before we used the config flow/UI option for setup? We did a small change that only displays the lock's state if it is actually provided by the car:
https://github.com/home-assistant/core/blob/dev/homeassistant/components/bmw_connected_drive/lock.py#L65-L72

If no status is provided, HA would "guess" a state which of course is not correct. Therefore we changed it to report *unkown* states which are the best info we got.
The open/close services will work even if your car does not provide the lock's current state.

**Comment by doodlebro** [comment]
So, based on my status.txt you are saying my car does not support/return the lock status? Kind of makes sense since the Connected Drive app doesn't really display the status either.

I guess I was just used to the HA "guessed" state that used to exist (though I did notice it displaying the wrong state plenty of times). Thanks for explaining that, no bug here.

**Comment by rikroe** [comment]
Thanks, I'll close this issue then!
